// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function Enroll(total_samples: number, data: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3155577541, total_samples, data) as any;
    return $resultPromise;
}

export function Init(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2515768019) as any;
    return $resultPromise;
}

export function Verify(): Promise<boolean | null> & { cancel(): void } {
    let $resultPromise = $Call.ByID(820259972) as any;
    return $resultPromise;
}
