// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class Finger {
    "ID": number;
    "OwnedBy": User;
    "Data": string;

    /** Creates a new Finger instance. */
    constructor($$source: Partial<Finger> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("OwnedBy" in $$source)) {
            this["OwnedBy"] = (new User());
        }
        if (!("Data" in $$source)) {
            this["Data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Finger instance from a string or object.
     */
    static createFrom($$source: any = {}): Finger {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("OwnedBy" in $$parsedSource) {
            $$parsedSource["OwnedBy"] = $$createField1_0($$parsedSource["OwnedBy"]);
        }
        return new Finger($$parsedSource as Partial<Finger>);
    }
}

export class User {
    "ID": string;
    "Name": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}

// Private type creation functions
const $$createType0 = User.createFrom;
